// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe0NsfGx5Dh0lYV_J5olcQlJrcCjXeUSk',
    appId: '1:666549893394:web:b41ff6856aa94c79041bcb',
    messagingSenderId: '666549893394',
    projectId: 'hobby-club-78807',
    authDomain: 'hobby-club-78807.firebaseapp.com',
    storageBucket: 'hobby-club-78807.firebasestorage.app',
    measurementId: 'G-R0PSJ58XTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9WQ-kmYzGrnKcFIa--L4AZRk5e2IXIxw',
    appId: '1:666549893394:android:7d9a7bba480c96cb041bcb',
    messagingSenderId: '666549893394',
    projectId: 'hobby-club-78807',
    storageBucket: 'hobby-club-78807.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb0tJQooEgoALS-e-5CSgfdsEav1YGnyY',
    appId: '1:666549893394:ios:2bae9f828088ca28041bcb',
    messagingSenderId: '666549893394',
    projectId: 'hobby-club-78807',
    storageBucket: 'hobby-club-78807.firebasestorage.app',
    iosClientId: '666549893394-o5u26559no3pni8ed5epliqvumep31jc.apps.googleusercontent.com',
    iosBundleId: 'com.example.hoppyClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb0tJQooEgoALS-e-5CSgfdsEav1YGnyY',
    appId: '1:666549893394:ios:2bae9f828088ca28041bcb',
    messagingSenderId: '666549893394',
    projectId: 'hobby-club-78807',
    storageBucket: 'hobby-club-78807.firebasestorage.app',
    iosClientId: '666549893394-o5u26559no3pni8ed5epliqvumep31jc.apps.googleusercontent.com',
    iosBundleId: 'com.example.hoppyClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe0NsfGx5Dh0lYV_J5olcQlJrcCjXeUSk',
    appId: '1:666549893394:web:ced6f91fcb665b97041bcb',
    messagingSenderId: '666549893394',
    projectId: 'hobby-club-78807',
    authDomain: 'hobby-club-78807.firebaseapp.com',
    storageBucket: 'hobby-club-78807.firebasestorage.app',
    measurementId: 'G-XWHY59CHG2',
  );
}
